/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 palmera.gltf 
Author: Next Spring (https://sketchfab.com/NextSpring)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/realistic-palm-tree-10-free-576ae63fa3e445939b52eba4a5ca96dc
Title: Realistic Palm Tree 10 (Free)
*/

import React, { useRef } from 'react';
import { useFrame } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF('/palmera.gltf');

  // Rotación automática usando useFrame
  useFrame(() => {
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.003; // Ajusta la velocidad de rotación aquí
    }
  });

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Palm_123_Palm_Trunk_0.geometry} material={materials.Palm_Trunk} />
        <mesh geometry={nodes.Palm_123_Palm_Bark_0.geometry} material={materials.Palm_Bark} />
        <mesh geometry={nodes.Palm_123_Palm_Leaf_0.geometry} material={materials.Palm_Leaf} />
      </group>
    </group>
  );
}

useGLTF.preload('/palmera.gltf');
